// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score-segment.proto

package com.nils.grpc.scoresegment;

/**
 * Protobuf type {@code scoresegment.ScoreSegmentResponse}
 */
public  final class ScoreSegmentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scoresegment.ScoreSegmentResponse)
    ScoreSegmentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScoreSegmentResponse.newBuilder() to construct.
  private ScoreSegmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScoreSegmentResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScoreSegmentResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (scoreSegment_ != null) {
              subBuilder = scoreSegment_.toBuilder();
            }
            scoreSegment_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(scoreSegment_);
              scoreSegment_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nils.grpc.scoresegment.ScoreSegmentResponse.class, com.nils.grpc.scoresegment.ScoreSegmentResponse.Builder.class);
  }

  public static final int SCORE_SEGMENT_FIELD_NUMBER = 1;
  private com.google.protobuf.UInt64Value scoreSegment_;
  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  public boolean hasScoreSegment() {
    return scoreSegment_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  public com.google.protobuf.UInt64Value getScoreSegment() {
    return scoreSegment_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : scoreSegment_;
  }
  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  public com.google.protobuf.UInt64ValueOrBuilder getScoreSegmentOrBuilder() {
    return getScoreSegment();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scoreSegment_ != null) {
      output.writeMessage(1, getScoreSegment());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scoreSegment_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getScoreSegment());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nils.grpc.scoresegment.ScoreSegmentResponse)) {
      return super.equals(obj);
    }
    com.nils.grpc.scoresegment.ScoreSegmentResponse other = (com.nils.grpc.scoresegment.ScoreSegmentResponse) obj;

    boolean result = true;
    result = result && (hasScoreSegment() == other.hasScoreSegment());
    if (hasScoreSegment()) {
      result = result && getScoreSegment()
          .equals(other.getScoreSegment());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasScoreSegment()) {
      hash = (37 * hash) + SCORE_SEGMENT_FIELD_NUMBER;
      hash = (53 * hash) + getScoreSegment().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nils.grpc.scoresegment.ScoreSegmentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scoresegment.ScoreSegmentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scoresegment.ScoreSegmentResponse)
      com.nils.grpc.scoresegment.ScoreSegmentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nils.grpc.scoresegment.ScoreSegmentResponse.class, com.nils.grpc.scoresegment.ScoreSegmentResponse.Builder.class);
    }

    // Construct using com.nils.grpc.scoresegment.ScoreSegmentResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (scoreSegmentBuilder_ == null) {
        scoreSegment_ = null;
      } else {
        scoreSegment_ = null;
        scoreSegmentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentResponse_descriptor;
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentResponse getDefaultInstanceForType() {
      return com.nils.grpc.scoresegment.ScoreSegmentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentResponse build() {
      com.nils.grpc.scoresegment.ScoreSegmentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentResponse buildPartial() {
      com.nils.grpc.scoresegment.ScoreSegmentResponse result = new com.nils.grpc.scoresegment.ScoreSegmentResponse(this);
      if (scoreSegmentBuilder_ == null) {
        result.scoreSegment_ = scoreSegment_;
      } else {
        result.scoreSegment_ = scoreSegmentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nils.grpc.scoresegment.ScoreSegmentResponse) {
        return mergeFrom((com.nils.grpc.scoresegment.ScoreSegmentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nils.grpc.scoresegment.ScoreSegmentResponse other) {
      if (other == com.nils.grpc.scoresegment.ScoreSegmentResponse.getDefaultInstance()) return this;
      if (other.hasScoreSegment()) {
        mergeScoreSegment(other.getScoreSegment());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nils.grpc.scoresegment.ScoreSegmentResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nils.grpc.scoresegment.ScoreSegmentResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.UInt64Value scoreSegment_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> scoreSegmentBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public boolean hasScoreSegment() {
      return scoreSegmentBuilder_ != null || scoreSegment_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public com.google.protobuf.UInt64Value getScoreSegment() {
      if (scoreSegmentBuilder_ == null) {
        return scoreSegment_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : scoreSegment_;
      } else {
        return scoreSegmentBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public Builder setScoreSegment(com.google.protobuf.UInt64Value value) {
      if (scoreSegmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scoreSegment_ = value;
        onChanged();
      } else {
        scoreSegmentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public Builder setScoreSegment(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (scoreSegmentBuilder_ == null) {
        scoreSegment_ = builderForValue.build();
        onChanged();
      } else {
        scoreSegmentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public Builder mergeScoreSegment(com.google.protobuf.UInt64Value value) {
      if (scoreSegmentBuilder_ == null) {
        if (scoreSegment_ != null) {
          scoreSegment_ =
            com.google.protobuf.UInt64Value.newBuilder(scoreSegment_).mergeFrom(value).buildPartial();
        } else {
          scoreSegment_ = value;
        }
        onChanged();
      } else {
        scoreSegmentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public Builder clearScoreSegment() {
      if (scoreSegmentBuilder_ == null) {
        scoreSegment_ = null;
        onChanged();
      } else {
        scoreSegment_ = null;
        scoreSegmentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getScoreSegmentBuilder() {
      
      onChanged();
      return getScoreSegmentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getScoreSegmentOrBuilder() {
      if (scoreSegmentBuilder_ != null) {
        return scoreSegmentBuilder_.getMessageOrBuilder();
      } else {
        return scoreSegment_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : scoreSegment_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getScoreSegmentFieldBuilder() {
      if (scoreSegmentBuilder_ == null) {
        scoreSegmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getScoreSegment(),
                getParentForChildren(),
                isClean());
        scoreSegment_ = null;
      }
      return scoreSegmentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scoresegment.ScoreSegmentResponse)
  }

  // @@protoc_insertion_point(class_scope:scoresegment.ScoreSegmentResponse)
  private static final com.nils.grpc.scoresegment.ScoreSegmentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nils.grpc.scoresegment.ScoreSegmentResponse();
  }

  public static com.nils.grpc.scoresegment.ScoreSegmentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScoreSegmentResponse>
      PARSER = new com.google.protobuf.AbstractParser<ScoreSegmentResponse>() {
    @java.lang.Override
    public ScoreSegmentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScoreSegmentResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScoreSegmentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScoreSegmentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nils.grpc.scoresegment.ScoreSegmentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

