// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score-segment.proto

package com.nils.grpc.scoresegment;

public final class ScoreSegment {
  private ScoreSegment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scoresegment_ScoreSegmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scoresegment_ScoreSegmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023score-segment.proto\022\014scoresegment\032\036goo" +
      "gle/protobuf/wrappers.proto\032\037google/prot" +
      "obuf/timestamp.proto\"F\n\023ScoreSegmentRequ" +
      "est\022/\n\tid_number\030\001 \001(\0132\034.google.protobuf" +
      ".UInt64Value\"K\n\024ScoreSegmentResponse\0223\n\r" +
      "score_segment\030\001 \001(\0132\034.google.protobuf.UI" +
      "nt64Value\"\207\001\n\035ScoreSegmentExceptionRespo" +
      "nse\022-\n\ttimestamp\030\001 \001(\0132\032.google.protobuf" +
      ".Timestamp\0227\n\nerror_code\030\002 \001(\0162#.scorese" +
      "gment.ScoreSegmentErrorCode*R\n\025ScoreSegm" +
      "entErrorCode\022\033\n\027INVALID_ID_NUMBER_VALUE\020" +
      "\000\022\034\n\030ID_NUMBER_CANNOT_BE_NULL\020\0012w\n\023Score" +
      "SegmentService\022`\n\025calculateScoreSegment\022" +
      "!.scoresegment.ScoreSegmentRequest\032\".sco" +
      "resegment.ScoreSegmentResponse\"\000B\036\n\032com." +
      "nils.grpc.scoresegmentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_scoresegment_ScoreSegmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scoresegment_ScoreSegmentRequest_descriptor,
        new java.lang.String[] { "IdNumber", });
    internal_static_scoresegment_ScoreSegmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_scoresegment_ScoreSegmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scoresegment_ScoreSegmentResponse_descriptor,
        new java.lang.String[] { "ScoreSegment", });
    internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_scoresegment_ScoreSegmentExceptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_scoresegment_ScoreSegmentExceptionResponse_descriptor,
        new java.lang.String[] { "Timestamp", "ErrorCode", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
