// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score-segment.proto

package com.nils.grpc.scoresegment;

public interface ScoreSegmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scoresegment.ScoreSegmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  boolean hasIdNumber();
  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  com.google.protobuf.UInt64Value getIdNumber();
  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getIdNumberOrBuilder();
}
