// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score-segment.proto

package com.nils.grpc.scoresegment;

public interface ScoreSegmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scoresegment.ScoreSegmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  boolean hasScoreSegment();
  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  com.google.protobuf.UInt64Value getScoreSegment();
  /**
   * <code>.google.protobuf.UInt64Value score_segment = 1;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getScoreSegmentOrBuilder();
}
