// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score-segment.proto

package com.nils.grpc.scoresegment;

/**
 * Protobuf type {@code scoresegment.ScoreSegmentRequest}
 */
public  final class ScoreSegmentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scoresegment.ScoreSegmentRequest)
    ScoreSegmentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScoreSegmentRequest.newBuilder() to construct.
  private ScoreSegmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScoreSegmentRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScoreSegmentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (idNumber_ != null) {
              subBuilder = idNumber_.toBuilder();
            }
            idNumber_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(idNumber_);
              idNumber_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nils.grpc.scoresegment.ScoreSegmentRequest.class, com.nils.grpc.scoresegment.ScoreSegmentRequest.Builder.class);
  }

  public static final int ID_NUMBER_FIELD_NUMBER = 1;
  private com.google.protobuf.UInt64Value idNumber_;
  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  public boolean hasIdNumber() {
    return idNumber_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  public com.google.protobuf.UInt64Value getIdNumber() {
    return idNumber_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : idNumber_;
  }
  /**
   * <code>.google.protobuf.UInt64Value id_number = 1;</code>
   */
  public com.google.protobuf.UInt64ValueOrBuilder getIdNumberOrBuilder() {
    return getIdNumber();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idNumber_ != null) {
      output.writeMessage(1, getIdNumber());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idNumber_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIdNumber());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nils.grpc.scoresegment.ScoreSegmentRequest)) {
      return super.equals(obj);
    }
    com.nils.grpc.scoresegment.ScoreSegmentRequest other = (com.nils.grpc.scoresegment.ScoreSegmentRequest) obj;

    boolean result = true;
    result = result && (hasIdNumber() == other.hasIdNumber());
    if (hasIdNumber()) {
      result = result && getIdNumber()
          .equals(other.getIdNumber());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIdNumber()) {
      hash = (37 * hash) + ID_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getIdNumber().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.nils.grpc.scoresegment.ScoreSegmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nils.grpc.scoresegment.ScoreSegmentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scoresegment.ScoreSegmentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scoresegment.ScoreSegmentRequest)
      com.nils.grpc.scoresegment.ScoreSegmentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nils.grpc.scoresegment.ScoreSegmentRequest.class, com.nils.grpc.scoresegment.ScoreSegmentRequest.Builder.class);
    }

    // Construct using com.nils.grpc.scoresegment.ScoreSegmentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idNumberBuilder_ == null) {
        idNumber_ = null;
      } else {
        idNumber_ = null;
        idNumberBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nils.grpc.scoresegment.ScoreSegment.internal_static_scoresegment_ScoreSegmentRequest_descriptor;
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentRequest getDefaultInstanceForType() {
      return com.nils.grpc.scoresegment.ScoreSegmentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentRequest build() {
      com.nils.grpc.scoresegment.ScoreSegmentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nils.grpc.scoresegment.ScoreSegmentRequest buildPartial() {
      com.nils.grpc.scoresegment.ScoreSegmentRequest result = new com.nils.grpc.scoresegment.ScoreSegmentRequest(this);
      if (idNumberBuilder_ == null) {
        result.idNumber_ = idNumber_;
      } else {
        result.idNumber_ = idNumberBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nils.grpc.scoresegment.ScoreSegmentRequest) {
        return mergeFrom((com.nils.grpc.scoresegment.ScoreSegmentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nils.grpc.scoresegment.ScoreSegmentRequest other) {
      if (other == com.nils.grpc.scoresegment.ScoreSegmentRequest.getDefaultInstance()) return this;
      if (other.hasIdNumber()) {
        mergeIdNumber(other.getIdNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.nils.grpc.scoresegment.ScoreSegmentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.nils.grpc.scoresegment.ScoreSegmentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.UInt64Value idNumber_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> idNumberBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public boolean hasIdNumber() {
      return idNumberBuilder_ != null || idNumber_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public com.google.protobuf.UInt64Value getIdNumber() {
      if (idNumberBuilder_ == null) {
        return idNumber_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : idNumber_;
      } else {
        return idNumberBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public Builder setIdNumber(com.google.protobuf.UInt64Value value) {
      if (idNumberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        idNumber_ = value;
        onChanged();
      } else {
        idNumberBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public Builder setIdNumber(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (idNumberBuilder_ == null) {
        idNumber_ = builderForValue.build();
        onChanged();
      } else {
        idNumberBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public Builder mergeIdNumber(com.google.protobuf.UInt64Value value) {
      if (idNumberBuilder_ == null) {
        if (idNumber_ != null) {
          idNumber_ =
            com.google.protobuf.UInt64Value.newBuilder(idNumber_).mergeFrom(value).buildPartial();
        } else {
          idNumber_ = value;
        }
        onChanged();
      } else {
        idNumberBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public Builder clearIdNumber() {
      if (idNumberBuilder_ == null) {
        idNumber_ = null;
        onChanged();
      } else {
        idNumber_ = null;
        idNumberBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getIdNumberBuilder() {
      
      onChanged();
      return getIdNumberFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getIdNumberOrBuilder() {
      if (idNumberBuilder_ != null) {
        return idNumberBuilder_.getMessageOrBuilder();
      } else {
        return idNumber_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : idNumber_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value id_number = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getIdNumberFieldBuilder() {
      if (idNumberBuilder_ == null) {
        idNumberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getIdNumber(),
                getParentForChildren(),
                isClean());
        idNumber_ = null;
      }
      return idNumberBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scoresegment.ScoreSegmentRequest)
  }

  // @@protoc_insertion_point(class_scope:scoresegment.ScoreSegmentRequest)
  private static final com.nils.grpc.scoresegment.ScoreSegmentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nils.grpc.scoresegment.ScoreSegmentRequest();
  }

  public static com.nils.grpc.scoresegment.ScoreSegmentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScoreSegmentRequest>
      PARSER = new com.google.protobuf.AbstractParser<ScoreSegmentRequest>() {
    @java.lang.Override
    public ScoreSegmentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScoreSegmentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScoreSegmentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScoreSegmentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nils.grpc.scoresegment.ScoreSegmentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

